// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SystemSetting is the predicate function for systemsetting builders.
type SystemSetting func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
