// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mail-admin/houduan/ent/schema"
	"mail-admin/houduan/ent/systemsetting"
	"mail-admin/houduan/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	systemsettingFields := schema.SystemSetting{}.Fields()
	_ = systemsettingFields
	// systemsettingDescKey is the schema descriptor for key field.
	systemsettingDescKey := systemsettingFields[0].Descriptor()
	// systemsetting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	systemsetting.KeyValidator = systemsettingDescKey.Validators[0].(func(string) error)
	// systemsettingDescValue is the schema descriptor for value field.
	systemsettingDescValue := systemsettingFields[1].Descriptor()
	// systemsetting.DefaultValue holds the default value on creation for the value field.
	systemsetting.DefaultValue = systemsettingDescValue.Default.(string)
	// systemsettingDescCreatedAt is the schema descriptor for created_at field.
	systemsettingDescCreatedAt := systemsettingFields[2].Descriptor()
	// systemsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	systemsetting.DefaultCreatedAt = systemsettingDescCreatedAt.Default.(func() time.Time)
	// systemsettingDescUpdatedAt is the schema descriptor for updated_at field.
	systemsettingDescUpdatedAt := systemsettingFields[3].Descriptor()
	// systemsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systemsetting.DefaultUpdatedAt = systemsettingDescUpdatedAt.Default.(func() time.Time)
	// systemsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systemsetting.UpdateDefaultUpdatedAt = systemsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// userDescAvatarURL is the schema descriptor for avatar_url field.
	userDescAvatarURL := userFields[2].Descriptor()
	// user.DefaultAvatarURL holds the default value on creation for the avatar_url field.
	user.DefaultAvatarURL = userDescAvatarURL.Default.(string)
	// userDescBalance is the schema descriptor for balance field.
	userDescBalance := userFields[3].Descriptor()
	// user.DefaultBalance holds the default value on creation for the balance field.
	user.DefaultBalance = userDescBalance.Default.(float64)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[5].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescEnabled is the schema descriptor for enabled field.
	userDescEnabled := userFields[6].Descriptor()
	// user.DefaultEnabled holds the default value on creation for the enabled field.
	user.DefaultEnabled = userDescEnabled.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
